entity_share_server.channel.*:
  type: config_entity
  label: 'Channel config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    channel_entity_type:
      type: string
      label: 'Channel entity type'
    channel_bundle:
      type: string
      label: 'Channel bundle'
    channel_langcode:
      type: string
      label: 'Channel langcode'
    channel_filters:
      type: sequence
      label: 'Channel filters'
      nullable: true
      sequence:
        type: entity_share_server.filter
        label: 'Filters'
    channel_groups:
      type: sequence
      label: 'Channel groups'
      nullable: true
      sequence:
        type: entity_share_server.group
        label: 'Groups'
    channel_sorts:
      type: sequence
      label: 'Channel sorts'
      nullable: true
      sequence:
        type: entity_share_server.sort
        label: 'Sorts'
    authorized_users:
      type: sequence
      label: 'Authorized users UUID'
      nullable: true
      sequence:
        type: string
        label: 'UUID'

entity_share_server.filter:
  type: mapping
  label: 'Filter'
  mapping:
    path:
      type: string
      label: 'Path'
    operator:
      type: string
      label: 'Operator'
    memberof:
      type: string
      label: 'Member of'
      nullable: true
    value:
      type: sequence
      label: 'Values'
      nullable: true
      sequence:
        type: string
        label: 'Value'

entity_share_server.sort:
  type: mapping
  label: 'Sort'
  mapping:
    path:
      type: string
      label: 'Path'
    direction:
      type: string
      label: 'Direction'
    weight:
      type: integer
      label: 'Weight'

entity_share_server.group:
  type: mapping
  label: 'Group'
  mapping:
    conjunction:
      type: string
      label: 'Conjunction'
    memberof:
      type: string
      label: 'Member of'
