google_tag.settings:
  type: config_object
  mapping:
    container_id:
      type: string
      label: 'Container ID'
    path_toggle:
      type: string
      label: 'Add snippet on specific paths'
    path_list:
      type: string
      label: 'Listed paths'
    role_toggle:
      type: string
      label: 'Add snippet for specific roles'
    role_list:
      type: sequence
      label: 'Selected roles'
      sequence:
        type: string
        label: 'Role'
    status_toggle:
      type: string
      label: 'Add snippet for specific statuses'
    status_list:
      type: string
      label: 'Listed statuses'
    compact_snippet:
      type: boolean
      label: 'Compact the JavaScript snippet'
    include_file:
      type: boolean
      label: 'Include the snippet as a file'
    rebuild_snippets:
      type: boolean
      label: 'Recreate snippets on cache rebuild'
    debug_output:
      type: boolean
      label: 'Show debug output'
    data_layer:
      type: string
      label: 'Data layer'
    include_classes:
      type: boolean
      label: 'Add classes to the data layer'
    whitelist_classes:
      type: string
      label: 'White-listed classes'
    blacklist_classes:
      type: string
      label: 'Black-listed classes'
    include_environment:
      type: boolean
      label: 'Include an environment'
    environment_id:
      type: string
      label: 'Environment ID'
    environment_token:
      type: string
      label: 'Environment token'

