<?php

/**
 * @file
 * Provides configurable blocks for a Twitter feed.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twitter_block_help($route_name, RouteMatchInterface $route_match) {
  $help_text = '';
  switch ($route_name) {
    case 'help.page.twitter_block':
      $help_text = '<p>' . t('This module provides configurable blocks for a Twitter feed.') . '</p>';
      return $help_text;
  }
}
