language: php
php:
  - 7.0
cache:
  bundler: true
  directories:
    - $HOME/tmp/drush
    - $HOME/.bundle
    - $HOME/.composer
    - $HOME/downloads
  apt: true

git:
 depth: 10000

# This creates a build with each php environment. 6 builds in total.
env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin"


# This will create the database
mysql:
  database: drupal
  username: root
  encoding: utf8

# To be able to run a webbrowser
# If we need anything more powerful
# than e.g. phantomjs
before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer global require "hirak/prestissimo:^0.3"
  - sudo apt-get update -qq > /dev/null
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "phantomjs --version"

install:
  # Make sure we don't fail when checking out projects
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host git.drupal.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Forward the errors to the syslog so we can print them
  - echo "error_log=syslog" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Get latest Drupal 8 core
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --branch 8.2.x https://git.drupal.org/project/drupal.git
  - cd $TRAVIS_BUILD_DIR/../drupal
  - composer install
  - composer config repositories.drupal composer https://packages.drupal.org/8
  # For daily development we'll test github repository.
  #- composer require drupal/conditional_fields:1.x-dev
  - composer require drush/drush
  # Patch template.
  #########################################
  # to be removed once #2824932 is resolved
  #- cd modules/search_api
  #- curl https://www.drupal.org/files/issues/2824932.patch | patch -p1
  #- cd $TRAVIS_BUILD_DIR/../drupal
  #########################################

before_script:
  # Start the built-in php web server (mysql is already started) and
  # suppress web-server access logs output.
  - php -S localhost:8888 ./vendor/drush/drush/commands/runserver/d8-rs-router.php >& /dev/null &
  # Install the site
  - ./vendor/bin/drush -v site-install minimal --db-url=mysql://root:@localhost/drupal --yes
  - ./vendor/bin/drush en conditional_fields -y
  - ./vendor/bin/drush en --yes simpletest
  # Therefore we have to install the test modules before the tests.
  - cp -R core/modules/system/tests/modules/entity_test core/modules/system/entity_test
  # start phantomjs with gastonjs
  - phantomjs --ssl-protocol=any --ignore-ssl-errors=true vendor/jcalderonzumba/gastonjs/src/Client/main.js 8510 1600 1080 > /tmp/pantomjs.out 2>&1 &

script:
  # Run the tests
  - cd $TRAVIS_BUILD_DIR/../drupal
  - export SIMPLETEST_DB=mysql://root:@localhost/drupal
  - export SIMPLETEST_BASE_URL=http://localhost:8888
  # Execute tests via phpunit.
  - ./vendor/bin/phpunit -c core --group conditional_fields | tee ; export TEST_PHPUNIT=${PIPESTATUS[0]} ; echo $TEST_PHPUNIT
  # Execute tests - Alternative way.
  - php core/scripts/run-tests.sh --verbose --color --non-html --concurrency 8 --php `which php` --url http://localhost:8888 --directory modules/contrib/conditional_fields/tests/src/Unit/ | tee /tmp/test.txt | grep passes; export TEST_EXIT=${PIPESTATUS[0]} ; echo $TEST_EXIT
  #- ./vendor/bin/phpunit -c core --group search_api --testsuite functional --verbose | tee ; export TEST_PHPUNIT=${PIPESTATUS[0]} ; echo $TEST_PHPUNIT
  - cd $TRAVIS_BUILD_DIR/../drupal
  # Re-enable when trying to get CodeSniffer doesn't return a 403 anymore.
  #- /home/travis/.composer/vendor/bin/phpcs --standard=/home/travis/.composer/vendor/drupal/coder/coder_sniffer/Drupal --extensions=php,inc,test,module,install --ignore=css/ $TRAVIS_BUILD_DIR/../drupal/modules/conditional_fields
  #- php -i | grep 'php.ini'
  # Check if we had fails in the run-tests.sh script
  # Exit with the inverted value, because if there are no fails found, it will exit with 1 and for us that\
  # is a good thing so invert it to 0. Travis has some issues with the exclamation mark in front so we have to fiddle a
  # bit.
  # Also make the grep case insensitive and fail on run-tests.sh regular fails as well on fatal errors.
  - TEST_OUTPUT=$(! egrep -i "([0-9]+ fails)|(Fatal erro)|([0-9]+ exceptions)" /tmp/test.txt > /dev/null)$?
  # Exit the build
  - echo $TEST_EXIT
  - echo $TEST_OUTPUT
  - echo $TEST_PHPUNIT
  #- if [ $TEST_EXIT -ne 0 ]; then cat /tmp/test.txt; fi
  #- if [ $TEST_EXIT -eq 0 ] && [ $TEST_OUTPUT -eq 0 ] && [ $TEST_PHPUNIT -eq 0 ]; then exit 0; else exit 1; fi
  - if [ $TEST_OUTPUT -eq 0 ] && [ $TEST_PHPUNIT -eq 0 ]; then exit 0; else exit 1; fi
