features:
  node_user_picture: false
  comment_user_picture: false
  comment_user_verification: false
  favicon: true
logo:
  use_default: false
  path: 'public://relativity_web_logo.png'
favicon:
  use_default: true
