palette:
  top: '#ececec'
  bottom: '#acacac'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#000000'
  text: '#3b3b3b'
  link: '#0071B3'
logo: 'public://color/bartik-4fa14111/logo.svg'
stylesheets:
  - 'public://color/bartik-4fa14111/colors.css'
files:
  - 'public://color/bartik-4fa14111/logo.svg'
  - 'public://color/bartik-4fa14111/colors.css'
