module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  auto_entitylabel: 0
  automated_cron: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  block_visibility_groups_admin: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_update: 0
  config_update_ui: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  extlink: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  link: 0
  link_attributes: 0
  linkit: 0
  menu_ui: 0
  nocurrent_pass: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  pathauto: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  simple_gmap: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  svg_formatter: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
